[package]
name = "solagate-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
solagate = { path = "../../programs/onchain_gateway" }
