[package]
name = "solagate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["no-entrypoint"]
no-entrypoint = []

[dependencies]
borsh = { workspace = true }
solana-program = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
solana-sdk = { workspace = true }
